export interface CountryCoordinates {
  country_code: string;
  lat: number;
  lon: number;
  name: string;
}

export const COUNTRY_COORDINATES: CountryCoordinates[] = [
    { country_code: "AF", lat: 33, lon: 65, name: "Afghanistan" },
    { country_code: "AL", lat: 41, lon: 20, name: "Albania" },
    { country_code: "DZ", lat: 28, lon: 3, name: "Algeria" },
    { country_code: "AO", lat: -12.5, lon: 18.5, name: "Angola" },
    { country_code: "AR", lat: -34, lon: -64, name: "Argentina" },
    { country_code: "AM", lat: 40, lon: 45, name: "Armenia" },
    { country_code: "AU", lat: -27, lon: 133, name: "Australia" },
    { country_code: "AT", lat: 47.3333, lon: 13.3333, name: "Austria" },
    { country_code: "AZ", lat: 40.5, lon: 47.5, name: "Azerbaijan" },
    { country_code: "BD", lat: 24, lon: 90, name: "Bangladesh" },
    { country_code: "BY", lat: 53, lon: 28, name: "Belarus" },
    { country_code: "BE", lat: 50.8333, lon: 4, name: "Belgium" },
    { country_code: "BZ", lat: 17.25, lon: -88.75, name: "Belize" },
    { country_code: "BJ", lat: 9.5, lon: 2.25, name: "Benin" },
    { country_code: "BT", lat: 27.5, lon: 90.5, name: "Bhutan" },
    { country_code: "BO", lat: -17, lon: -65, name: "Bolivia" },
    { country_code: "BA", lat: 44, lon: 18, name: "Bosnia and Herzegovina" },
    { country_code: "BW", lat: -22, lon: 24, name: "Botswana" },
    { country_code: "BR", lat: -10, lon: -55, name: "Brazil" },
    { country_code: "BN", lat: 4.5, lon: 114.6667, name: "Brunei Darussalam" },
    { country_code: "BG", lat: 43, lon: 25, name: "Bulgaria" },
    { country_code: "BF", lat: 13, lon: -2, name: "Burkina Faso" },
    { country_code: "BI", lat: -3.5, lon: 30, name: "Burundi" },
    { country_code: "KH", lat: 13, lon: 105, name: "Cambodia" },
    { country_code: "CM", lat: 6, lon: 12, name: "Cameroon" },
    { country_code: "CA", lat: 60, lon: -95, name: "Canada" },
    { country_code: "CF", lat: 7, lon: 21, name: "Central African Republic" },
    { country_code: "TD", lat: 15, lon: 19, name: "Chad" },
    { country_code: "CL", lat: -30, lon: -71, name: "Chile" },
    { country_code: "CN", lat: 35, lon: 105, name: "China" },
    { country_code: "CO", lat: 4, lon: -72, name: "Colombia" },
    { country_code: "CG", lat: -1, lon: 15, name: "Congo" },
    { country_code: "CR", lat: 10, lon: -84, name: "Costa Rica" },
    { country_code: "HR", lat: 45.1667, lon: 15.5, name: "Croatia" },
    { country_code: "CU", lat: 21.5, lon: -80, name: "Cuba" },
    { country_code: "CY", lat: 35, lon: 33, name: "Cyprus" },
    { country_code: "CZ", lat: 49.75, lon: 15.5, name: "Czech Republic" },
    { country_code: "DK", lat: 56, lon: 10, name: "Denmark" },
    { country_code: "DJ", lat: 11.5, lon: 43, name: "Djibouti" },
    { country_code: "DO", lat: 19, lon: -70.6667, name: "Dominican Republic" },
    { country_code: "EC", lat: -2, lon: -77.5, name: "Ecuador" },
    { country_code: "EG", lat: 27, lon: 30, name: "Egypt" },
    { country_code: "SV", lat: 13.8333, lon: -88.9167, name: "El Salvador" },
    { country_code: "GQ", lat: 2, lon: 10, name: "Equatorial Guinea" },
    { country_code: "ER", lat: 15, lon: 39, name: "Eritrea" },
    { country_code: "EE", lat: 59, lon: 26, name: "Estonia" },
    { country_code: "ET", lat: 8, lon: 38, name: "Ethiopia" },
    { country_code: "FI", lat: 64, lon: 26, name: "Finland" },
    { country_code: "FR", lat: 46, lon: 2, name: "France" },
    { country_code: "GA", lat: -1, lon: 11.75, name: "Gabon" },
    { country_code: "GE", lat: 42, lon: 43.5, name: "Georgia" },
    { country_code: "DE", lat: 51, lon: 9, name: "Germany" },
    { country_code: "GH", lat: 8, lon: -2, name: "Ghana" },
    { country_code: "GR", lat: 39, lon: 22, name: "Greece" },
    { country_code: "GT", lat: 15.5, lon: -90.25, name: "Guatemala" },
    { country_code: "GN", lat: 11, lon: -10, name: "Guinea" },
    { country_code: "GW", lat: 12, lon: -15, name: "Guinea-Bissau" },
    { country_code: "GY", lat: 5, lon: -59, name: "Guyana" },
    { country_code: "HT", lat: 19, lon: -72.4167, name: "Haiti" },
    { country_code: "HN", lat: 15, lon: -86.5, name: "Honduras" },
    { country_code: "HU", lat: 47, lon: 20, name: "Hungary" },
    { country_code: "IS", lat: 65, lon: -18, name: "Iceland" },
    { country_code: "IN", lat: 20, lon: 77, name: "India" },
    { country_code: "ID", lat: -5, lon: 120, name: "Indonesia" },
    { country_code: "IR", lat: 32, lon: 53, name: "Iran" },
    { country_code: "IQ", lat: 33, lon: 44, name: "Iraq" },
    { country_code: "IE", lat: 53, lon: -8, name: "Ireland" },
    { country_code: "IL", lat: 31.5, lon: 34.75, name: "Israel" },
    { country_code: "IT", lat: 42.8333, lon: 12.8333, name: "Italy" },
    { country_code: "JP", lat: 36, lon: 138, name: "Japan" },
    { country_code: "JO", lat: 31, lon: 36, name: "Jordan" },
    { country_code: "KZ", lat: 48, lon: 68, name: "Kazakhstan" },
    { country_code: "KE", lat: 1, lon: 38, name: "Kenya" },
    { country_code: "KR", lat: 37, lon: 127.5, name: "Korea, Republic of" },
    { country_code: "KW", lat: 29.3375, lon: 47.6581, name: "Kuwait" },
    { country_code: "KG", lat: 41, lon: 75, name: "Kyrgyzstan" },
    { country_code: "LV", lat: 57, lon: 25, name: "Latvia" },
    { country_code: "LB", lat: 33.8333, lon: 35.8333, name: "Lebanon" },
    { country_code: "LS", lat: -29.5, lon: 28.5, name: "Lesotho" },
    { country_code: "LR", lat: 6.5, lon: -9.5, name: "Liberia" },
    { country_code: "LY", lat: 25, lon: 17, name: "Libya" },
    { country_code: "LT", lat: 56, lon: 24, name: "Lithuania" },
    { country_code: "LU", lat: 49.75, lon: 6.1667, name: "Luxembourg" },
    { country_code: "MK", lat: 41.8333, lon: 22, name: "Macedonia" },
    { country_code: "MG", lat: -20, lon: 47, name: "Madagascar" },
    { country_code: "MW", lat: -13.5, lon: 34, name: "Malawi" },
    { country_code: "MY", lat: 2.5, lon: 112.5, name: "Malaysia" },
    { country_code: "ML", lat: 17, lon: -4, name: "Mali" },
    { country_code: "MR", lat: 20, lon: -12, name: "Mauritania" },
    { country_code: "MX", lat: 23, lon: -102, name: "Mexico" },
    { country_code: "MD", lat: 47, lon: 29, name: "Moldova" },
    { country_code: "MN", lat: 46, lon: 105, name: "Mongolia" },
    { country_code: "ME", lat: 42, lon: 19, name: "Montenegro" },
    { country_code: "MA", lat: 32, lon: -5, name: "Morocco" },
    { country_code: "MZ", lat: -18.25, lon: 35, name: "Mozambique" },
    { country_code: "MM", lat: 22, lon: 98, name: "Myanmar" },
    { country_code: "NA", lat: -22, lon: 17, name: "Namibia" },
    { country_code: "NP", lat: 28, lon: 84, name: "Nepal" },
    { country_code: "NL", lat: 52.5, lon: 5.75, name: "Netherlands" },
    { country_code: "NZ", lat: -41, lon: 174, name: "New Zealand" },
    { country_code: "NI", lat: 13, lon: -85, name: "Nicaragua" },
    { country_code: "NE", lat: 16, lon: 8, name: "Niger" },
    { country_code: "NG", lat: 10, lon: 8, name: "Nigeria" },
    { country_code: "NO", lat: 62, lon: 10, name: "Norway" },
    { country_code: "OM", lat: 21, lon: 57, name: "Oman" },
    { country_code: "PK", lat: 30, lon: 70, name: "Pakistan" },
    { country_code: "PA", lat: 9, lon: -80, name: "Panama" },
    { country_code: "PY", lat: -23, lon: -58, name: "Paraguay" },
    { country_code: "PE", lat: -10, lon: -76, name: "Peru" },
    { country_code: "PH", lat: 13, lon: 122, name: "Philippines" },
    { country_code: "PL", lat: 52, lon: 20, name: "Poland" },
    { country_code: "PT", lat: 39.5, lon: -8, name: "Portugal" },
    { country_code: "QA", lat: 25.5, lon: 51.25, name: "Qatar" },
    { country_code: "RO", lat: 46, lon: 25, name: "Romania" },
    { country_code: "RU", lat: 60, lon: 100, name: "Russian Federation" },
    { country_code: "RW", lat: -2, lon: 30, name: "Rwanda" },
    { country_code: "SA", lat: 25, lon: 45, name: "Saudi Arabia" },
    { country_code: "SN", lat: 14, lon: -14, name: "Senegal" },
    { country_code: "RS", lat: 44, lon: 21, name: "Serbia" },
    { country_code: "SL", lat: 8.5, lon: -11.5, name: "Sierra Leone" },
    { country_code: "SK", lat: 48.6667, lon: 19.5, name: "Slovakia" },
    { country_code: "SI", lat: 46, lon: 15, name: "Slovenia" },
    { country_code: "SO", lat: 10, lon: 49, name: "Somalia" },
    { country_code: "ZA", lat: -29, lon: 24, name: "South Africa" },
    { country_code: "ES", lat: 40, lon: -4, name: "Spain" },
    { country_code: "LK", lat: 7, lon: 81, name: "Sri Lanka" },
    { country_code: "SD", lat: 15, lon: 30, name: "Sudan" },
    { country_code: "SR", lat: 4, lon: -56, name: "Suriname" },
    { country_code: "SZ", lat: -26.5, lon: 31.5, name: "Swaziland" },
    { country_code: "SE", lat: 62, lon: 15, name: "Sweden" },
    { country_code: "CH", lat: 47, lon: 8, name: "Switzerland" },
    { country_code: "SY", lat: 35, lon: 38, name: "Syrian Arab Republic" },
    { country_code: "TW", lat: 23.5, lon: 121, name: "Taiwan" },
    { country_code: "TJ", lat: 39, lon: 71, name: "Tajikistan" },
    { country_code: "TZ", lat: -6, lon: 35, name: "Tanzania" },
    { country_code: "TH", lat: 15, lon: 100, name: "Thailand" },
    { country_code: "TG", lat: 8, lon: 1.1667, name: "Togo" },
    { country_code: "TN", lat: 34, lon: 9, name: "Tunisia" },
    { country_code: "TR", lat: 39, lon: 35, name: "Turkey" },
    { country_code: "TM", lat: 40, lon: 60, name: "Turkmenistan" },
    { country_code: "UG", lat: 1, lon: 32, name: "Uganda" },
    { country_code: "UA", lat: 49, lon: 32, name: "Ukraine" },
    { country_code: "AE", lat: 24, lon: 54, name: "United Arab Emirates" },
    { country_code: "GB", lat: 54, lon: -2, name: "United Kingdom" },
    { country_code: "US", lat: 38, lon: -97, name: "United States" },
    { country_code: "UY", lat: -33, lon: -56, name: "Uruguay" },
    { country_code: "UZ", lat: 41, lon: 64, name: "Uzbekistan" },
    { country_code: "VE", lat: 8, lon: -66, name: "Venezuela" },
    { country_code: "VN", lat: 16, lon: 106, name: "Vietnam" },
    { country_code: "YE", lat: 15, lon: 48, name: "Yemen" },
    { country_code: "ZM", lat: -15, lon: 30, name: "Zambia" },
    { country_code: "ZW", lat: -20, lon: 30, name: "Zimbabwe" },
];
